services:
  db_config:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: solarmap_db_config
    volumes:
      - .:/app
    working_dir: /app/src
    command: python db_config.py

  descarga:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: solarmap_descarga
    volumes:
      - .:/app
      - /Users/macbook/.cdsapirc:/root/.cdsapirc:ro
    working_dir: /app/src
    command: python descargar_radiacion.py

  limpieza_carga:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: solarmap_limpieza_carga
    volumes:
      - .:/app
    working_dir: /app/src
    command: bash -lc "python procesar_radiacion.py && python db_config.py"

  api_mapa:
    build:
      context: .
      dockerfile: Dockerfile.api_mapa
    ports:
      - "8000:8000"
    working_dir: /app/src

  web_mapa:
    build:
      context: .
      dockerfile: Dockerfile.web_mapa
    ports:
      - "8080:80"
    depends_on:
      - api_mapa
